#############################################################################
# Makefile for building: GraphBasedTraconSimulator.app/Contents/MacOS/GraphBasedTraconSimulator
# Generated by qmake (3.1) (Qt 5.11.2)
# Project:  GraphBasedTraconSimulator.pro
# Template: app
# Command: /Users/tristanlopus/Qt/5.11.2/clang_64/bin/qmake -o Makefile GraphBasedTraconSimulator.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk -mmacosx-version-min=10.11 -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -O2 -std=gnu++11 $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk -mmacosx-version-min=10.11 -Wall -W -fPIC $(DEFINES)
INCPATH       = -I. -I. -I../../../Qt/5.11.2/clang_64/lib/QtGui.framework/Headers -I../../../Qt/5.11.2/clang_64/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/AGL.framework/Headers -I../../../Qt/5.11.2/clang_64/mkspecs/macx-clang -F/Users/tristanlopus/Qt/5.11.2/clang_64/lib
QMAKE         = /Users/tristanlopus/Qt/5.11.2/clang_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /Users/tristanlopus/Qt/5.11.2/clang_64/bin/qmake -install qinstall
QINSTALL_PROGRAM = /Users/tristanlopus/Qt/5.11.2/clang_64/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = GraphBasedTraconSimulator1.0.0
DISTDIR = /Users/tristanlopus/Google\ Drive/Independent\ Study/GraphBasedTraconSimulator/.tmp/GraphBasedTraconSimulator1.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -stdlib=libc++ -headerpad_max_install_names $(EXPORT_ARCH_ARGS) -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk -mmacosx-version-min=10.11 -Wl,-rpath,@executable_path/Frameworks -Wl,-rpath,/Users/tristanlopus/Qt/5.11.2/clang_64/lib
LIBS          = $(SUBLIBS) -F/Users/tristanlopus/Qt/5.11.2/clang_64/lib -framework QtGui -framework QtCore -framework DiskArbitration -framework IOKit -framework OpenGL -framework AGL 
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = Aircraft.cpp \
		AircraftMoment.cpp \
		AircraftTarget.cpp \
		AirspaceGraph.cpp \
		Fix.cpp \
		GraphBasedTraconSimulator.cpp \
		main.cpp \
		Path.cpp \
		Position.cpp \
		Timer.cpp \
		utilities.cpp qrc_qml.cpp \
		qrc_Resources.cpp \
		moc_GraphBasedTraconSimulator.cpp
OBJECTS       = Aircraft.o \
		AircraftMoment.o \
		AircraftTarget.o \
		AirspaceGraph.o \
		Fix.o \
		GraphBasedTraconSimulator.o \
		main.o \
		Path.o \
		Position.o \
		Timer.o \
		utilities.o \
		qrc_qml.o \
		qrc_Resources.o \
		moc_GraphBasedTraconSimulator.o
DIST          = ../../../Qt/5.11.2/clang_64/mkspecs/features/spec_pre.prf \
		../../../Qt/5.11.2/clang_64/mkspecs/qdevice.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/features/device_config.prf \
		../../../Qt/5.11.2/clang_64/mkspecs/common/unix.conf \
		../../../Qt/5.11.2/clang_64/mkspecs/common/mac.conf \
		../../../Qt/5.11.2/clang_64/mkspecs/common/macx.conf \
		../../../Qt/5.11.2/clang_64/mkspecs/common/sanitize.conf \
		../../../Qt/5.11.2/clang_64/mkspecs/common/gcc-base.conf \
		../../../Qt/5.11.2/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../../Qt/5.11.2/clang_64/mkspecs/common/clang.conf \
		../../../Qt/5.11.2/clang_64/mkspecs/common/clang-mac.conf \
		../../../Qt/5.11.2/clang_64/mkspecs/qconfig.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_3danimation.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_charts.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_charts_private.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_datavisualization.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_networkauth.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_positioningquick.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_positioningquick_private.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_purchasing.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_repparser.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_repparser_private.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_service_support_private.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_texttospeech.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/features/qt_functions.prf \
		../../../Qt/5.11.2/clang_64/mkspecs/features/qt_config.prf \
		../../../Qt/5.11.2/clang_64/mkspecs/macx-clang/qmake.conf \
		../../../Qt/5.11.2/clang_64/mkspecs/features/spec_post.prf \
		../../../Qt/5.11.2/clang_64/mkspecs/features/exclusive_builds.prf \
		../../../Qt/5.11.2/clang_64/mkspecs/features/mac/sdk.prf \
		../../../Qt/5.11.2/clang_64/mkspecs/features/toolchain.prf \
		../../../Qt/5.11.2/clang_64/mkspecs/features/mac/toolchain.prf \
		../../../Qt/5.11.2/clang_64/mkspecs/features/default_pre.prf \
		../../../Qt/5.11.2/clang_64/mkspecs/features/mac/default_pre.prf \
		../../../Qt/5.11.2/clang_64/mkspecs/features/resolve_config.prf \
		../../../Qt/5.11.2/clang_64/mkspecs/features/default_post.prf \
		../../../Qt/5.11.2/clang_64/mkspecs/features/mac/default_post.prf \
		../../../Qt/5.11.2/clang_64/mkspecs/features/mac/objective_c.prf \
		../../../Qt/5.11.2/clang_64/mkspecs/features/mac/mac.prf \
		../../../Qt/5.11.2/clang_64/mkspecs/features/warn_on.prf \
		../../../Qt/5.11.2/clang_64/mkspecs/features/qt.prf \
		../../../Qt/5.11.2/clang_64/mkspecs/features/resources.prf \
		../../../Qt/5.11.2/clang_64/mkspecs/features/moc.prf \
		../../../Qt/5.11.2/clang_64/mkspecs/features/unix/opengl.prf \
		../../../Qt/5.11.2/clang_64/mkspecs/features/unix/thread.prf \
		../../../Qt/5.11.2/clang_64/mkspecs/features/qmake_use.prf \
		../../../Qt/5.11.2/clang_64/mkspecs/features/file_copies.prf \
		../../../Qt/5.11.2/clang_64/mkspecs/features/mac/rez.prf \
		../../../Qt/5.11.2/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		../../../Qt/5.11.2/clang_64/mkspecs/features/testcase_targets.prf \
		../../../Qt/5.11.2/clang_64/mkspecs/features/exceptions.prf \
		../../../Qt/5.11.2/clang_64/mkspecs/features/yacc.prf \
		../../../Qt/5.11.2/clang_64/mkspecs/features/lex.prf \
		GraphBasedTraconSimulator.pro Aircraft.h \
		AircraftMoment.h \
		AircraftTarget.h \
		AirspaceGraph.h \
		AppInfo.h \
		constants.h \
		CSVRow.hpp \
		Fix.h \
		GraphBasedTraconSimulator.h \
		Path.h \
		Position.h \
		Timer.h \
		trigMath.h \
		unitConverters.h \
		utilities.h \
		VectorMath.h Aircraft.cpp \
		AircraftMoment.cpp \
		AircraftTarget.cpp \
		AirspaceGraph.cpp \
		Fix.cpp \
		GraphBasedTraconSimulator.cpp \
		main.cpp \
		Path.cpp \
		Position.cpp \
		Timer.cpp \
		utilities.cpp
QMAKE_TARGET  = GraphBasedTraconSimulator
DESTDIR       = 
TARGET        = GraphBasedTraconSimulator.app/Contents/MacOS/GraphBasedTraconSimulator

####### Custom Variables
EXPORT_QMAKE_MAC_SDK = macosx
EXPORT_QMAKE_MAC_SDK_VERSION = 10.14
EXPORT_VALID_ARCHS = x86_64
EXPORT_ACTIVE_ARCHS = $(filter $(EXPORT_VALID_ARCHS), $(ARCHS))
EXPORT_ARCH_ARGS = $(foreach arch, $(if $(EXPORT_ACTIVE_ARCHS), $(EXPORT_ACTIVE_ARCHS), $(EXPORT_VALID_ARCHS)), -arch $(arch))


include /Users/tristanlopus/Qt/5.11.2/clang_64/mkspecs/features/mac/sdk.mk
first: all
####### Build rules

$(TARGET):  $(OBJECTS)  
	@test -d GraphBasedTraconSimulator.app/Contents/MacOS/ || mkdir -p GraphBasedTraconSimulator.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: GraphBasedTraconSimulator.pro ../../../Qt/5.11.2/clang_64/mkspecs/macx-clang/qmake.conf ../../../Qt/5.11.2/clang_64/mkspecs/features/spec_pre.prf \
		../../../Qt/5.11.2/clang_64/mkspecs/qdevice.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/features/device_config.prf \
		../../../Qt/5.11.2/clang_64/mkspecs/common/unix.conf \
		../../../Qt/5.11.2/clang_64/mkspecs/common/mac.conf \
		../../../Qt/5.11.2/clang_64/mkspecs/common/macx.conf \
		../../../Qt/5.11.2/clang_64/mkspecs/common/sanitize.conf \
		../../../Qt/5.11.2/clang_64/mkspecs/common/gcc-base.conf \
		../../../Qt/5.11.2/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../../Qt/5.11.2/clang_64/mkspecs/common/clang.conf \
		../../../Qt/5.11.2/clang_64/mkspecs/common/clang-mac.conf \
		../../../Qt/5.11.2/clang_64/mkspecs/qconfig.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_3danimation.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_charts.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_charts_private.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_datavisualization.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_networkauth.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_positioningquick.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_positioningquick_private.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_purchasing.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_repparser.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_repparser_private.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_service_support_private.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_texttospeech.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../Qt/5.11.2/clang_64/mkspecs/features/qt_functions.prf \
		../../../Qt/5.11.2/clang_64/mkspecs/features/qt_config.prf \
		../../../Qt/5.11.2/clang_64/mkspecs/macx-clang/qmake.conf \
		../../../Qt/5.11.2/clang_64/mkspecs/features/spec_post.prf \
		../../../Qt/5.11.2/clang_64/mkspecs/features/exclusive_builds.prf \
		../../../Qt/5.11.2/clang_64/mkspecs/features/mac/sdk.prf \
		../../../Qt/5.11.2/clang_64/mkspecs/features/toolchain.prf \
		../../../Qt/5.11.2/clang_64/mkspecs/features/mac/toolchain.prf \
		../../../Qt/5.11.2/clang_64/mkspecs/features/default_pre.prf \
		../../../Qt/5.11.2/clang_64/mkspecs/features/mac/default_pre.prf \
		../../../Qt/5.11.2/clang_64/mkspecs/features/resolve_config.prf \
		../../../Qt/5.11.2/clang_64/mkspecs/features/default_post.prf \
		../../../Qt/5.11.2/clang_64/mkspecs/features/mac/default_post.prf \
		../../../Qt/5.11.2/clang_64/mkspecs/features/mac/objective_c.prf \
		../../../Qt/5.11.2/clang_64/mkspecs/features/mac/mac.prf \
		../../../Qt/5.11.2/clang_64/mkspecs/features/warn_on.prf \
		../../../Qt/5.11.2/clang_64/mkspecs/features/qt.prf \
		../../../Qt/5.11.2/clang_64/mkspecs/features/resources.prf \
		../../../Qt/5.11.2/clang_64/mkspecs/features/moc.prf \
		../../../Qt/5.11.2/clang_64/mkspecs/features/unix/opengl.prf \
		../../../Qt/5.11.2/clang_64/mkspecs/features/unix/thread.prf \
		../../../Qt/5.11.2/clang_64/mkspecs/features/qmake_use.prf \
		../../../Qt/5.11.2/clang_64/mkspecs/features/file_copies.prf \
		../../../Qt/5.11.2/clang_64/mkspecs/features/mac/rez.prf \
		../../../Qt/5.11.2/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		../../../Qt/5.11.2/clang_64/mkspecs/features/testcase_targets.prf \
		../../../Qt/5.11.2/clang_64/mkspecs/features/exceptions.prf \
		../../../Qt/5.11.2/clang_64/mkspecs/features/yacc.prf \
		../../../Qt/5.11.2/clang_64/mkspecs/features/lex.prf \
		GraphBasedTraconSimulator.pro \
		qml/qml.qrc \
		Resources/Resources.qrc \
		../../../Qt/5.11.2/clang_64/lib/QtGui.framework/QtGui.prl \
		../../../Qt/5.11.2/clang_64/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -o Makefile GraphBasedTraconSimulator.pro
../../../Qt/5.11.2/clang_64/mkspecs/features/spec_pre.prf:
../../../Qt/5.11.2/clang_64/mkspecs/qdevice.pri:
../../../Qt/5.11.2/clang_64/mkspecs/features/device_config.prf:
../../../Qt/5.11.2/clang_64/mkspecs/common/unix.conf:
../../../Qt/5.11.2/clang_64/mkspecs/common/mac.conf:
../../../Qt/5.11.2/clang_64/mkspecs/common/macx.conf:
../../../Qt/5.11.2/clang_64/mkspecs/common/sanitize.conf:
../../../Qt/5.11.2/clang_64/mkspecs/common/gcc-base.conf:
../../../Qt/5.11.2/clang_64/mkspecs/common/gcc-base-mac.conf:
../../../Qt/5.11.2/clang_64/mkspecs/common/clang.conf:
../../../Qt/5.11.2/clang_64/mkspecs/common/clang-mac.conf:
../../../Qt/5.11.2/clang_64/mkspecs/qconfig.pri:
../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_3danimation.pri:
../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri:
../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_3dcore.pri:
../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri:
../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_3dextras.pri:
../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri:
../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_3dinput.pri:
../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri:
../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_3dlogic.pri:
../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_3dquick.pri:
../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri:
../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri:
../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri:
../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri:
../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri:
../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri:
../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_3drender.pri:
../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_3drender_private.pri:
../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri:
../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_charts.pri:
../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_charts_private.pri:
../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri:
../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_core.pri:
../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_core_private.pri:
../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_datavisualization.pri:
../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri:
../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_dbus.pri:
../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_designer.pri:
../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_edid_support_private.pri:
../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri:
../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_gamepad.pri:
../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri:
../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri:
../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_gui.pri:
../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_help.pri:
../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_help_private.pri:
../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_location.pri:
../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_location_private.pri:
../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_macextras.pri:
../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_network.pri:
../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_network_private.pri:
../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_networkauth.pri:
../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri:
../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_nfc.pri:
../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_opengl.pri:
../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_positioning.pri:
../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_positioningquick.pri:
../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_positioningquick_private.pri:
../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_purchasing.pri:
../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri:
../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_qml.pri:
../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_quick.pri:
../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_remoteobjects.pri:
../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_remoteobjects_private.pri:
../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_repparser.pri:
../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_repparser_private.pri:
../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_script.pri:
../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_script_private.pri:
../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_scxml.pri:
../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_scxml_private.pri:
../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_sensors.pri:
../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_serialbus.pri:
../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri:
../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_serialport.pri:
../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_service_support_private.pri:
../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_sql.pri:
../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_svg.pri:
../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_testlib.pri:
../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_texttospeech.pri:
../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri:
../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri:
../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_uiplugin.pri:
../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_uitools.pri:
../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_webchannel.pri:
../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_webengine.pri:
../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_webengine_private.pri:
../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_webenginecore.pri:
../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_websockets.pri:
../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_webview.pri:
../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_webview_private.pri:
../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_widgets.pri:
../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_xml.pri:
../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../../Qt/5.11.2/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../../Qt/5.11.2/clang_64/mkspecs/features/qt_functions.prf:
../../../Qt/5.11.2/clang_64/mkspecs/features/qt_config.prf:
../../../Qt/5.11.2/clang_64/mkspecs/macx-clang/qmake.conf:
../../../Qt/5.11.2/clang_64/mkspecs/features/spec_post.prf:
../../../Qt/5.11.2/clang_64/mkspecs/features/exclusive_builds.prf:
../../../Qt/5.11.2/clang_64/mkspecs/features/mac/sdk.prf:
../../../Qt/5.11.2/clang_64/mkspecs/features/toolchain.prf:
../../../Qt/5.11.2/clang_64/mkspecs/features/mac/toolchain.prf:
../../../Qt/5.11.2/clang_64/mkspecs/features/default_pre.prf:
../../../Qt/5.11.2/clang_64/mkspecs/features/mac/default_pre.prf:
../../../Qt/5.11.2/clang_64/mkspecs/features/resolve_config.prf:
../../../Qt/5.11.2/clang_64/mkspecs/features/default_post.prf:
../../../Qt/5.11.2/clang_64/mkspecs/features/mac/default_post.prf:
../../../Qt/5.11.2/clang_64/mkspecs/features/mac/objective_c.prf:
../../../Qt/5.11.2/clang_64/mkspecs/features/mac/mac.prf:
../../../Qt/5.11.2/clang_64/mkspecs/features/warn_on.prf:
../../../Qt/5.11.2/clang_64/mkspecs/features/qt.prf:
../../../Qt/5.11.2/clang_64/mkspecs/features/resources.prf:
../../../Qt/5.11.2/clang_64/mkspecs/features/moc.prf:
../../../Qt/5.11.2/clang_64/mkspecs/features/unix/opengl.prf:
../../../Qt/5.11.2/clang_64/mkspecs/features/unix/thread.prf:
../../../Qt/5.11.2/clang_64/mkspecs/features/qmake_use.prf:
../../../Qt/5.11.2/clang_64/mkspecs/features/file_copies.prf:
../../../Qt/5.11.2/clang_64/mkspecs/features/mac/rez.prf:
../../../Qt/5.11.2/clang_64/mkspecs/features/mac/asset_catalogs.prf:
../../../Qt/5.11.2/clang_64/mkspecs/features/testcase_targets.prf:
../../../Qt/5.11.2/clang_64/mkspecs/features/exceptions.prf:
../../../Qt/5.11.2/clang_64/mkspecs/features/yacc.prf:
../../../Qt/5.11.2/clang_64/mkspecs/features/lex.prf:
GraphBasedTraconSimulator.pro:
qml/qml.qrc:
Resources/Resources.qrc:
../../../Qt/5.11.2/clang_64/lib/QtGui.framework/QtGui.prl:
../../../Qt/5.11.2/clang_64/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile GraphBasedTraconSimulator.pro

qmake_all: FORCE

GraphBasedTraconSimulator.app/Contents/PkgInfo: 
	@test -d GraphBasedTraconSimulator.app/Contents || mkdir -p GraphBasedTraconSimulator.app/Contents
	@$(DEL_FILE) GraphBasedTraconSimulator.app/Contents/PkgInfo
	@echo "APPL????" > GraphBasedTraconSimulator.app/Contents/PkgInfo
GraphBasedTraconSimulator.app/Contents/Resources/empty.lproj: 
	@test -d GraphBasedTraconSimulator.app/Contents/Resources || mkdir -p GraphBasedTraconSimulator.app/Contents/Resources
	@touch GraphBasedTraconSimulator.app/Contents/Resources/empty.lproj
	
GraphBasedTraconSimulator.app/Contents/Info.plist: 
	@test -d GraphBasedTraconSimulator.app/Contents || mkdir -p GraphBasedTraconSimulator.app/Contents
	@$(DEL_FILE) GraphBasedTraconSimulator.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,\$${QMAKE_SHORT_VERSION},1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,\$${QMAKE_FULL_VERSION},1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" -e "s,@BUNDLEIDENTIFIER@,tristanlopus.GraphBasedTraconSimulator,g" -e "s,\$${PRODUCT_BUNDLE_IDENTIFIER},tristanlopus.GraphBasedTraconSimulator,g" -e "s,\$${MACOSX_DEPLOYMENT_TARGET},10.11,g" -e "s,\$${IPHONEOS_DEPLOYMENT_TARGET},,g" -e "s,\$${TVOS_DEPLOYMENT_TARGET},,g" -e "s,\$${WATCHOS_DEPLOYMENT_TARGET},,g" -e "s,@ICON@,,g" -e "s,\$${ASSETCATALOG_COMPILER_APPICON_NAME},,g" -e "s,@EXECUTABLE@,GraphBasedTraconSimulator,g" -e "s,@LIBRARY@,GraphBasedTraconSimulator,g" -e "s,\$${EXECUTABLE_NAME},GraphBasedTraconSimulator,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" ../../../Qt/5.11.2/clang_64/mkspecs/macx-clang/Info.plist.app >GraphBasedTraconSimulator.app/Contents/Info.plist

all: Makefile \
		GraphBasedTraconSimulator.app/Contents/PkgInfo \
		GraphBasedTraconSimulator.app/Contents/Resources/empty.lproj \
		GraphBasedTraconSimulator.app/Contents/Info.plist $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents qml/qml.qrc Resources/Resources.qrc $(DISTDIR)/
	$(COPY_FILE) --parents ../../../Qt/5.11.2/clang_64/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents Aircraft.h AircraftMoment.h AircraftTarget.h AirspaceGraph.h AppInfo.h constants.h CSVRow.hpp Fix.h GraphBasedTraconSimulator.h Path.h Position.h Timer.h trigMath.h unitConverters.h utilities.h VectorMath.h $(DISTDIR)/
	$(COPY_FILE) --parents Aircraft.cpp AircraftMoment.cpp AircraftTarget.cpp AirspaceGraph.cpp Fix.cpp GraphBasedTraconSimulator.cpp main.cpp Path.cpp Position.cpp Timer.cpp utilities.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r GraphBasedTraconSimulator.app
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_qml.cpp qrc_Resources.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_qml.cpp qrc_Resources.cpp
qrc_qml.cpp: qml/qml.qrc \
		../../../Qt/5.11.2/clang_64/bin/rcc \
		qml/main.qml
	/Users/tristanlopus/Qt/5.11.2/clang_64/bin/rcc -name qml qml/qml.qrc -o qrc_qml.cpp

qrc_Resources.cpp: Resources/Resources.qrc \
		../../../Qt/5.11.2/clang_64/bin/rcc \
		Resources/AppIcon.png
	/Users/tristanlopus/Qt/5.11.2/clang_64/bin/rcc -name Resources Resources/Resources.qrc -o qrc_Resources.cpp

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: ../../../Qt/5.11.2/clang_64/mkspecs/features/data/dummy.cpp
	/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -pipe -stdlib=libc++ -O2 -std=gnu++11 $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk -mmacosx-version-min=10.11 -Wall -W -dM -E -o moc_predefs.h ../../../Qt/5.11.2/clang_64/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_GraphBasedTraconSimulator.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_GraphBasedTraconSimulator.cpp
moc_GraphBasedTraconSimulator.cpp: AirspaceGraph.h \
		Fix.h \
		Position.h \
		Path.h \
		Aircraft.h \
		AircraftTarget.h \
		AircraftMoment.h \
		Timer.h \
		GraphBasedTraconSimulator.h \
		moc_predefs.h \
		../../../Qt/5.11.2/clang_64/bin/moc
	/Users/tristanlopus/Qt/5.11.2/clang_64/bin/moc $(DEFINES) --include '/Users/tristanlopus/Google Drive/Independent Study/GraphBasedTraconSimulator/moc_predefs.h' -I/Users/tristanlopus/Qt/5.11.2/clang_64/mkspecs/macx-clang -I'/Users/tristanlopus/Google Drive/Independent Study/GraphBasedTraconSimulator' -I'/Users/tristanlopus/Google Drive/Independent Study/GraphBasedTraconSimulator' -I/Users/tristanlopus/Qt/5.11.2/clang_64/lib/QtGui.framework/Headers -I/Users/tristanlopus/Qt/5.11.2/clang_64/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/10.0.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include -F/Users/tristanlopus/Qt/5.11.2/clang_64/lib GraphBasedTraconSimulator.h -o moc_GraphBasedTraconSimulator.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

Aircraft.o: Aircraft.cpp Aircraft.h \
		AircraftTarget.h \
		AircraftMoment.h \
		Position.h \
		Fix.h \
		Path.h \
		Timer.h \
		constants.h \
		vectorMath.h \
		trigMath.h \
		unitConverters.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Aircraft.o Aircraft.cpp

AircraftMoment.o: AircraftMoment.cpp AircraftMoment.h \
		Position.h \
		Fix.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o AircraftMoment.o AircraftMoment.cpp

AircraftTarget.o: AircraftTarget.cpp AircraftTarget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o AircraftTarget.o AircraftTarget.cpp

AirspaceGraph.o: AirspaceGraph.cpp AirspaceGraph.h \
		Fix.h \
		Position.h \
		Path.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o AirspaceGraph.o AirspaceGraph.cpp

Fix.o: Fix.cpp Fix.h \
		Position.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Fix.o Fix.cpp

GraphBasedTraconSimulator.o: GraphBasedTraconSimulator.cpp ../../../Qt/5.11.2/clang_64/lib/QtCore.framework/Headers/QTimer \
		../../../Qt/5.11.2/clang_64/lib/QtCore.framework/Headers/qtimer.h \
		../../../Qt/5.11.2/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../../Qt/5.11.2/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		GraphBasedTraconSimulator.h \
		AirspaceGraph.h \
		Fix.h \
		Position.h \
		Path.h \
		Aircraft.h \
		AircraftTarget.h \
		AircraftMoment.h \
		Timer.h \
		CSVRow.hpp \
		utilities.h \
		constants.h \
		VectorMath.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o GraphBasedTraconSimulator.o GraphBasedTraconSimulator.cpp

main.o: main.cpp ../../../Qt/5.11.2/clang_64/lib/QtCore.framework/Headers/QSettings \
		../../../Qt/5.11.2/clang_64/lib/QtCore.framework/Headers/qsettings.h \
		../../../Qt/5.11.2/clang_64/lib/QtGui.framework/Headers/QGuiApplication \
		../../../Qt/5.11.2/clang_64/lib/QtGui.framework/Headers/qguiapplication.h \
		../../../Qt/5.11.2/clang_64/lib/QtCore.framework/Headers/QCommandLineParser \
		../../../Qt/5.11.2/clang_64/lib/QtCore.framework/Headers/qcommandlineparser.h \
		../../../Qt/5.11.2/clang_64/lib/QtCore.framework/Headers/QDir \
		../../../Qt/5.11.2/clang_64/lib/QtCore.framework/Headers/qdir.h \
		AppInfo.h \
		GraphBasedTraconSimulator.h \
		AirspaceGraph.h \
		Fix.h \
		Position.h \
		Path.h \
		Aircraft.h \
		AircraftTarget.h \
		AircraftMoment.h \
		Timer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

Path.o: Path.cpp Path.h \
		Fix.h \
		Position.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Path.o Path.cpp

Position.o: Position.cpp Position.h \
		trigMath.h \
		constants.h \
		vectorMath.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Position.o Position.cpp

Timer.o: Timer.cpp Timer.h \
		constants.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Timer.o Timer.cpp

utilities.o: utilities.cpp utilities.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o utilities.o utilities.cpp

qrc_qml.o: qrc_qml.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_qml.o qrc_qml.cpp

qrc_Resources.o: qrc_Resources.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_Resources.o qrc_Resources.cpp

moc_GraphBasedTraconSimulator.o: moc_GraphBasedTraconSimulator.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_GraphBasedTraconSimulator.o moc_GraphBasedTraconSimulator.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

